# Generated by Django 4.1.4 on 2023-01-18 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machineLearning', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageModel',
        ),
    ]
