# Generated by Django 4.1.4 on 2023-01-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineLearning', '0003_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
